import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { checkBioCreateLimit, checkApiLimit, getRateLimitHeaders } from '@/lib/security/rate-limiter';
import { createBioPageSchema } from '@/validations/bio';
import { writeBioAuditLog } from '@/lib/audit';
import { BIO_DEFAULTS } from '@/lib/constants';

const MAX_SLUG_RETRIES = 3;

/**
 * POST /api/bio - Create a new bio-link page
 *
 * One page per user is enforced by a UNIQUE constraint on owner_id.
 */
export async function POST(request: NextRequest) {
  const supabase = await createClient();

  // Check authentication
  const { data: { user }, error: authError } = await supabase.auth.getUser();
  if (authError || !user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  // Check rate limit
  const rateLimit = checkBioCreateLimit(user.id);
  if (!rateLimit.success) {
    return NextResponse.json(
      { error: 'Rate limit exceeded' },
      { status: 429, headers: getRateLimitHeaders(rateLimit) }
    );
  }

  try {
    const body = await request.json();

    // Validate input
    const parsed = createBioPageSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json(
        { error: 'Validation error', details: parsed.error.flatten() },
        { status: 400 }
      );
    }

    const {
      title,
      bio,
      slug,
      theme,
      button_style,
      custom_bg_color,
      custom_text_color,
      custom_accent_color,
      analytics_enabled,
      create_qr,
    } = parsed.data;

    // Check if user already has a bio page
    const { data: existing, error: existingError } = await supabase
      .from('bio_link_pages')
      .select('id')
      .eq('owner_id', user.id)
      .is('deleted_at', null)
      .maybeSingle();

    if (existing) {
      return NextResponse.json(
        { error: 'You already have a bio page. Each user can have one bio page.' },
        { status: 409 }
      );
    }

    // Generate slug with retry logic
    let finalSlug = slug;
    let page: { id: string; slug: string } | null = null;

    for (let attempt = 0; attempt < MAX_SLUG_RETRIES; attempt++) {
      if (!finalSlug) {
        const { data: slugData, error: slugError } = await supabase
          .rpc('generate_bio_unique_slug');

        if (slugError) {
          return NextResponse.json(
            { error: 'Failed to generate slug' },
            { status: 500 }
          );
        }
        finalSlug = slugData;
      }

      const { data: created, error: createError } = await supabase
        .from('bio_link_pages')
        .insert({
          owner_id: user.id,
          title,
          bio: bio || null,
          slug: finalSlug!,
          theme,
          button_style,
          custom_bg_color: custom_bg_color || null,
          custom_text_color: custom_text_color || null,
          custom_accent_color: custom_accent_color || null,
          analytics_enabled,
        })
        .select('id, slug')
        .single();

      if (createError) {
        // Unique slug violation — retry with a new slug
        if (createError.code === '23505' && !slug) {
          finalSlug = undefined;
          continue;
        }
        // Unique owner_id violation — user already has a page
        if (createError.code === '23505') {
          return NextResponse.json(
            { error: 'You already have a bio page.' },
            { status: 409 }
          );
        }
        console.error('Failed to create bio page:', createError.message, createError.code, createError.details);
        return NextResponse.json(
          {
            error: 'Failed to create bio page',
            ...(process.env.NODE_ENV === 'development' && {
              debug: createError.message,
              code: createError.code,
              details: createError.details,
            }),
          },
          { status: 500 }
        );
      }

      page = created;
      break;
    }

    if (!page) {
      return NextResponse.json(
        { error: 'Failed to create bio page after multiple attempts' },
        { status: 500 }
      );
    }

    // Optionally create a QR code pointing to this bio page
    let qrCodeId: string | null = null;
    if (create_qr) {
      const pageUrl = `${process.env.NEXT_PUBLIC_APP_URL || ''}/p/${page.slug}`;

      const { data: qr, error: qrError } = await supabase
        .from('qr_codes')
        .insert({
          owner_id: user.id,
          name: `QR for ${title}`,
          mode: 'managed' as const,
          slug: null, // Will be generated by trigger — actually we need to generate one
          destination_url: pageUrl,
          analytics_enabled: true,
        })
        .select('id')
        .single();

      // QR codes with mode='managed' require a slug, so generate one
      if (qrError) {
        // Non-critical: bio page was created, QR is optional
        console.error('Failed to create QR for bio page:', qrError.message);
      } else if (qr) {
        // Generate a slug for the QR code
        const { data: qrSlug } = await supabase.rpc('generate_qr_unique_slug');
        if (qrSlug) {
          await supabase
            .from('qr_codes')
            .update({ slug: qrSlug })
            .eq('id', qr.id);
        }

        qrCodeId = qr.id;
        // Link the QR to the bio page
        await supabase
          .from('bio_link_pages')
          .update({ qr_code_id: qr.id })
          .eq('id', page.id);
      }
    }

    // Write audit log (fire-and-forget)
    writeBioAuditLog({
      pageId: page.id,
      actorId: user.id,
      action: 'created',
      newValue: { title, slug: page.slug, theme, create_qr },
      ipAddress: request.headers.get('x-forwarded-for')?.split(',')[0] || null,
      userAgent: request.headers.get('user-agent') || null,
    });

    const pageUrl = `${process.env.NEXT_PUBLIC_APP_URL || ''}/p/${page.slug}`;

    return NextResponse.json({
      id: page.id,
      slug: page.slug,
      page_url: pageUrl,
      qr_code_id: qrCodeId,
    }, {
      status: 201,
      headers: getRateLimitHeaders(rateLimit),
    });

  } catch (error) {
    const message = error instanceof Error ? error.message : 'unknown error';
    const stack = error instanceof Error ? error.stack : undefined;
    console.error('API error:', message, stack);
    return NextResponse.json(
      {
        error: 'Internal server error',
        ...(process.env.NODE_ENV === 'development' && { debug: message, stack }),
      },
      { status: 500 }
    );
  }
}

/**
 * GET /api/bio - Get the user's bio page
 */
export async function GET(request: NextRequest) {
  const supabase = await createClient();

  // Check authentication
  const { data: { user }, error: authError } = await supabase.auth.getUser();
  if (authError || !user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  // Check rate limit
  const rateLimit = checkApiLimit(user.id);
  if (!rateLimit.success) {
    return NextResponse.json(
      { error: 'Rate limit exceeded' },
      { status: 429, headers: getRateLimitHeaders(rateLimit) }
    );
  }

  try {
    const { data: page, error } = await supabase
      .from('bio_link_pages')
      .select('*, bio_link_items(*)')
      .eq('owner_id', user.id)
      .is('deleted_at', null)
      .order('sort_order', { referencedTable: 'bio_link_items', ascending: true })
      .maybeSingle();

    if (error || !page) {
      return NextResponse.json({ data: null }, {
        headers: getRateLimitHeaders(rateLimit),
      });
    }

    return NextResponse.json({ data: page }, {
      headers: getRateLimitHeaders(rateLimit),
    });

  } catch (error) {
    console.error('API error:', error instanceof Error ? error.message : 'unknown error');
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}
